volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    image: koba101/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - media:/media/
      - static:/backend_static/
      - ./ingredients.json:/app/ingredients.json:ro

  frontend:
    env_file: .env
    image: koba101/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    image: koba101/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/staticfiles/
      - media:/media/